name: Promote develop -> main

on:
  push:
    branches: [ develop ]

permissions:
  contents: write
  pull-requests: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
          clean: true

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Sync develop with main
        run: |
          git fetch origin main
          git checkout develop
          git merge origin/main --no-edit || echo "No changes needed"
          git push origin develop || echo "Nothing to push"

      - name: Create PR to main
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: "chore: promote develop → main"
          branch: promote/develop-to-main
          base: main
          title: "Automated: promote develop → main"
          body: "PR created automatically after pushing to develop. Kept in sync with latest develop commits."
          labels: ci, auto-merge
          delete-branch: true
          draft: false

      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-number
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
